package kap8;

import javax.swing.*;
import java.awt.*;

public class TemperaturUmrechner extends JFrame {
    private JTextField textFieldCelsius;
    private JButton buttonUmrechnen;
    private JTextField textFieldFahrenheit;
    private JPanel panelMain;
    private JRadioButton radioButtonCelsiusNachFahrenheit;
    private JRadioButton radioButtonFahrenheitNachCelsius;

    public TemperaturUmrechner() {
        setTitle("Temperatur-Umrechner");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(600, 400);
        setLocationRelativeTo(null);
        setContentPane(panelMain);
        setVisible(true);

        buttonUmrechnen.addActionListener(e -> {

            try {
                double c = checkInputText(textFieldCelsius.getText());
                berechne(c);
            } catch (EmptyStringException ex) {
                System.out.println("eingabefeld ist leer");
            } catch (MyNumberFormatException ex) {
                textFieldCelsius.setBackground(Color.RED);
                System.out.println("bitte geben sie eine gültige zahl ein");
            }
        });
    }

    private void berechne(double value) {
        textFieldCelsius.setBackground(Color.WHITE);
        if (radioButtonCelsiusNachFahrenheit.isSelected()) {
            double f = celsiusToFahrenheit(value);
            textFieldFahrenheit.setText("" + f);
        }
        if (radioButtonFahrenheitNachCelsius.isSelected()) {
            double f = fahrenheitToCelsius(value);
            textFieldFahrenheit.setText("" + f);
        }
    }

    private double checkInputText(String input) throws EmptyStringException, MyNumberFormatException {
        if (input.isEmpty()) {
            throw new EmptyStringException();
        }

        try {
            return Double.parseDouble(input);
        } catch (NumberFormatException ex) {
            throw new MyNumberFormatException();
        }
    }

    public double celsiusToFahrenheit(double celsius) {
        return celsius * 9 / 5 + 32;
    }

    public double fahrenheitToCelsius(double fahrenheit) {
        return (fahrenheit - 32) / 1.8;
    }

    public static void main(String[] args) {
        new TemperaturUmrechner();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(7, 3, new Insets(0, 0, 0, 0), -1, -1));
        textFieldCelsius = new JTextField();
        textFieldCelsius.setText("");
        panelMain.add(textFieldCelsius, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Temperatur in Grad Celsius:");
        panelMain.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonUmrechnen = new JButton();
        buttonUmrechnen.setText("Umrechnen");
        panelMain.add(buttonUmrechnen, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textFieldFahrenheit = new JTextField();
        textFieldFahrenheit.setEditable(false);
        panelMain.add(textFieldFahrenheit, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 2, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Temperatur in Grad Fahrenheit:");
        panelMain.add(label2, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        radioButtonCelsiusNachFahrenheit = new JRadioButton();
        radioButtonCelsiusNachFahrenheit.setText("Celsius nach Fahrenheit");
        panelMain.add(radioButtonCelsiusNachFahrenheit, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        radioButtonFahrenheitNachCelsius = new JRadioButton();
        radioButtonFahrenheitNachCelsius.setText("Fahrenheit nach Celsius");
        panelMain.add(radioButtonFahrenheitNachCelsius, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioButtonCelsiusNachFahrenheit);
        buttonGroup.add(radioButtonFahrenheitNachCelsius);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }

}
